package com.hpbr.bosszhipin.base;

import com.chad.library.adapter.base.entity.MultiItemEntity;
import net.bosszhipin.api.bean.BaseServerBean;

/* JADX INFO: loaded from: classes3.dex */
public abstract class GeekBaseCardBean extends BaseServerBean implements MultiItemEntity {
    public static final int FROM_BIZ_1109_SMALLCITY = 1;
    public static final int TYPE_1019_RCMD_CARD = 135;
    public static final int TYPE_1101_SIMILAR_LIST = 137;
    public static final int TYPE_1102_SIMILAR_LIST = 138;
    public static final int TYPE_1102_SIMILAR_LIST_GRAYB = 151;
    public static final int TYPE_1105_DISTANCE_FEED_BACK = 142;
    public static final int TYPE_1105_SETTING_HOME_ADDRESS = 143;
    public static final int TYPE_1105_UPDATE_LOCATION = 141;
    public static final int TYPE_1106_RCMD_NEAR_WITHOUT_OPTION = 144;
    public static final int TYPE_1106_RCMD_NEAR_WITH_OPTION = 145;
    public static final int TYPE_1107_SALARY_FEED_BACK = 147;
    public static final int TYPE_1107_THEME_ENTRANCE = 11071;
    public static final int TYPE_1109_SMALL_CITY_FILLCARD = 152;
    public static final int TYPE_1116_COMPANY_ENTRANCE = 154;
    public static final int TYPE_1117_HUNTER_ENTRANCE = 155;
    public static final int TYPE_1117_HUNTER_ENTRANCE_AB = 156;
    public static final int TYPE_1201_GPT_ADVANTAGE = 157;
    public static final int TYPE_1202_STU_ZONE_JOBCARDGRAY_BIG = 158;
    public static final int TYPE_1202_STU_ZONE_JOBCARDGRAY_FLOW = 159;
    public static final int TYPE_1219801_SIMILAR_LIST = 10010;
    public static final int TYPE_COLLECT_JOB_EMPTY = 6;
    public static final int TYPE_COM_SUBSCRIBE = 9;
    public static final int TYPE_CONTACT_TOP_TIP = 10;
    public static final int TYPE_EMPTY = 0;
    public static final int TYPE_F1_BOOK_KEEPING = 153;
    public static final int TYPE_F1_CARD_1008_HANDI = 125;
    public static final int TYPE_F1_CARD_1008_NEARBY = 123;
    public static final int TYPE_F1_CARD_808_BLUE_EXPECT_MULTI = 131;
    public static final int TYPE_F1_CARD_ADVERTISEMENT = 105;
    public static final int TYPE_F1_CARD_BLUE_COMPLETE_RESUME_TIP = 113;
    public static final int TYPE_F1_CARD_BLUE_EXPERIENCE = 117;
    public static final int TYPE_F1_CARD_BLUE_NOT_RECOMMEND = 120;
    public static final int TYPE_F1_CARD_CAREER_EMPTY = 202;
    public static final int TYPE_F1_CARD_CHARACTER_LABEL_ENTRY_NEW_STYLE = 146;
    public static final int TYPE_F1_CARD_CHARACTER_LABEL_ENTRY_NEW_STYLE_IN_JOB_LIST = 150;
    public static final int TYPE_F1_CARD_CITY_RECOMMEND = 116;
    public static final int TYPE_F1_CARD_COMPLETE_RESUME_TIP = 121;
    public static final int TYPE_F1_CARD_EMPTY = 200;
    public static final int TYPE_F1_CARD_GARBAGE_RESUME = 132;
    public static final int TYPE_F1_CARD_GET_LAYOUT = 112;
    public static final int TYPE_F1_CARD_GET_PIC = 111;
    public static final int TYPE_F1_CARD_INTERVIEW = 109;
    public static final int TYPE_F1_CARD_MIX_RECOMMEND = 115;
    public static final int TYPE_F1_CARD_SUPPLY_POSITION = 110;
    public static final int TYPE_F1_CARD_SUPPORT_NEARBY_ALL = 122;
    public static final int TYPE_F1_CARD_TRANSFER_CARD = 118;
    public static final int TYPE_F1_ERRO = 201;
    public static final int TYPE_F1_JOBCARD_ANXINBAO = 106;
    public static final int TYPE_F1_JOBCARD_ANXINBAO_GROUPA = 127;
    public static final int TYPE_F1_JOBCARD_ANXINBAO_GROUPB = 128;
    public static final int TYPE_F1_JOBCARD_ANXINBAO_GROUPC = 129;
    public static final int TYPE_F1_JOBCARD_DEFAULT = 100;
    public static final int TYPE_F1_JOBCARD_KEYWORD = 101;
    public static final int TYPE_F1_JOBCARD_LIVE = 104;
    public static final int TYPE_F1_JOBCARD_MIXED = 102;
    public static final int TYPE_F1_JOBCARD_MIXED_GRAY = 136;
    public static final int TYPE_F1_JOBCARD_RECOMMEND = 107;
    public static final int TYPE_F1_JOBCARD_TITAN = 130;
    public static final int TYPE_F1_JOBCARD_WORKER = 103;
    public static final int TYPE_F1_MATCH_POSITION = 133;
    public static final int TYPE_F1_VIVO_HANDI = 134;
    public static final int TYPE_F2_CARD_EMPTY = 203;
    public static final int TYPE_GEEK_F1_AI_JOB_ASSESSMENT = 10017;
    public static final int TYPE_GEEK_F1_AI_ROBOT = 161;
    public static final int TYPE_GEEK_F1_BANNER_QUERY_TEMPLATE1 = 1604;
    public static final int TYPE_GEEK_F1_BANNER_QUERY_TEMPLATE2 = 1605;
    public static final int TYPE_GEEK_F1_BANNER_QUERY_TEMPLATE3 = 1606;
    public static final int TYPE_GEEK_F1_BANNER_QUERY_TEMPLATE4 = 1607;
    public static final int TYPE_GEEK_F1_BANNER_QUERY_TEMPLATE5 = 1608;
    public static final int TYPE_GEEK_F1_BANNER_QUERY_TIPS_ADD_INDUSTRY_BANNER = 1601;
    public static final int TYPE_GEEK_F1_BANNER_QUERY_TIPS_ADD_SKILL_BANNER = 1603;
    public static final int TYPE_GEEK_F1_BANNER_QUERY_TIPS_SALARY_GUIDE_BANNER = 1600;
    public static final int TYPE_GEEK_F1_FEEDBACK = 10015;
    public static final int TYPE_GEEK_F1_JOB_RECOMMEND_INQUIRY = 10016;
    public static final int TYPE_GEEK_F1_MIX_BLUE_COLLAR_TOPIC_ZON = 10014;
    public static final int TYPE_GEEK_F1_OLD_USER_UPDATE_EXPECT = 10005;
    public static final int TYPE_GEEK_F1_RECOMMEND_AD_ADD_INDUSTRY = 10006;
    public static final int TYPE_GEEK_F1_RECOMMEND_AD_ADD_SKILL = 10011;
    public static final int TYPE_GEEK_F1_RECOMMEND_AD_EXPERIMENT_FOUR = 10003;
    public static final int TYPE_GEEK_F1_RECOMMEND_AD_EXPERIMENT_ONE = 10000;
    public static final int TYPE_GEEK_F1_RECOMMEND_AD_EXPERIMENT_THREE = 10002;
    public static final int TYPE_GEEK_F1_RECOMMEND_AD_EXPERIMENT_TWO = 10001;
    public static final int TYPE_GEEK_F1_RECOMMEND_AD_GUIDE_ADD_MORE_EXPECT = 10012;
    public static final int TYPE_GEEK_F1_REMOVE_FILTER = 10013;
    public static final int TYPE_GEEK_F1_RHINOCEROS_FACE_TO_FACE_LOOK_CHANCE = 10004;
    public static final int TYPE_GEEK_F1_SMALL_CITY_MIX_TOPIC_ZONE = 10009;
    public static final int TYPE_GEEK_F1_STUDENT_ADVERTISE = 200;
    public static final int TYPE_GEEK_F1_STUDENT_ANXINBAO = 1102;
    public static final int TYPE_GEEK_F1_STUDENT_ANXINBAO_A = 1103;
    public static final int TYPE_GEEK_F1_STUDENT_ANXINBAO_B = 1204;
    public static final int TYPE_GEEK_F1_STUDENT_ANXINBAO_C = 1205;
    public static final int TYPE_GEEK_F1_STUDENT_BANNER_HEADER = 702;
    public static final int TYPE_GEEK_F1_STUDENT_CARD_DEFAULT = 1001;
    public static final int TYPE_GEEK_F1_STUDENT_CARD_KEY_WORD = 1002;
    public static final int TYPE_GEEK_F1_STUDENT_CARD_WORKER = 1004;
    public static final int TYPE_GEEK_F1_STUDENT_CHAT_RECOMMEND = 1111;
    public static final int TYPE_GEEK_F1_STUDENT_CITY_RECOMMEND = 602;
    public static final int TYPE_GEEK_F1_STUDENT_DISTANCE_FOOTER = 705;
    public static final int TYPE_GEEK_F1_STUDENT_EMPTY = 700;
    public static final int TYPE_GEEK_F1_STUDENT_EMPTY_FOOTER = 704;
    public static final int TYPE_GEEK_F1_STUDENT_ERROR_DEFAULT = 706;
    public static final int TYPE_GEEK_F1_STUDENT_GET_PIC_1 = 500;
    public static final int TYPE_GEEK_F1_STUDENT_GET_PIC_2 = 501;
    public static final int TYPE_GEEK_F1_STUDENT_HANDI_CARD = 613;
    public static final int TYPE_GEEK_F1_STUDENT_NONE_JOB_HEADER = 701;
    public static final int TYPE_GEEK_F1_STUDENT_RECOMMEND = 1106;
    public static final int TYPE_GEEK_F1_STUDENT_SCHOOL_COMPANY_2 = 1110;
    public static final int TYPE_GEEK_F1_STUDENT_SUPPLY_POSITION_TIP = 300;
    public static final int TYPE_GEEK_F1_STUDENT_TIP_HEADER = 703;
    public static final int TYPE_GEEK_F1_STUDENT_TITAN = 1101;
    public static final int TYPE_GEEK_F1_STUDENT_TRANSFER_CARD = 604;
    public static final int TYPE_GEEK_F1_STUDENT_XIAOYUAN_DASHI = 707;
    public static final int TYPE_GEEK_F1_TOP_POSITION = 162;
    public static final int TYPE_GEEK_F2_BANNER_IMAGE = 4;
    public static final int TYPE_GEEK_F2_BOTTOM_TIP = 9;
    public static final int TYPE_GEEK_F2_GUESS_YOU_WANT = 7;
    public static final int TYPE_GEEK_F2_HEAD_TIP = 8;
    public static final int TYPE_GEEK_F2_INTERACT_JOB_CARD = 3;
    public static final int TYPE_GEEK_F2_INTEREST_JOB_TYPE = 20012;
    public static final int TYPE_GEEK_F2_LOOK_ALL = 2009;
    public static final int TYPE_GEEK_F2_PRIVACY_SETTING_CARD = 5;
    public static final int TYPE_GEEK_F2_RECOMMEND_DIVIDER = 20011;
    public static final int TYPE_GEEK_F2_TOP_EMPTY = 20010;
    public static final int TYPE_GEEK_F2_WHO_SEE_ME = 6;
    public static final int TYPE_GEEK_F2_WHO_SEE_ME_1019_GRAY = 61;
    public static final int TYPE_GEEK_HANDICAP_ZONE_GUIDE_CARD = 160;
    public static final int TYPE_GEEK_TUTORING_MODULE_CARD = 164;
    public static final int TYPE_HIGH_JOB_RECOMMEND = 7;
    public static final int TYPE_HIGH_JOB_SUBSCRIBE = 139;
    public static final int TYPE_INTERST_MULTI_CITY = 140;
    public static final int TYPE_JOB_CARD_BASE = 1;
    public static final int TYPE_JOB_CARD_F3_COMMON = 2;
    public static final int TYPE_JOB_CARD_F3_COMMON_NEW = 3;
    public static final int TYPE_JOB_CARD_F3_TIME_LINE = 4;
    public static final int TYPE_JOB_UPDATE_REMIND = 8;
    public static final int TYPE_STUDENT_CHAT_RECOMMEND_1125 = 1112;
    public static final int TYPE_STU_ZONE_JOB_CARD_EMPTY = 163;
    public static final long serialVersionUID = 3032558451819147107L;
    public int fromBiz;
    public int itemType;

    public GeekBaseCardBean(int i11) {
        this.itemType = i11;
    }

    @Override // com.chad.library.adapter.base.entity.MultiItemEntity
    public int getItemType() {
        return this.itemType;
    }
}